### ISSUE TITLE
Is Yabar aware Locale?

### ISSUE THREAD

**Issue by devedetti** [geommer/yabar#208]
Hi All, I'm a newbie Yabar's user (and wm too).

I launch bpswm with `exec bspwm` from `.xinitrc` and launch `yabar` from `bspwmrc`.
I'm using the YABAR_DATE on my bar, but it show the day and month names in english.

I want to see the it as **Miércoles 01 Mayo, 19:05** instead of **Wednesday 01 May, 19:05**.

How can I achieve this?
Thanks!

```bash
$ locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=es_AR.UTF-8
LC_TIME=es_AR.UTF-8
LC_COLLATE=en_US.UTF-8
LC_MONETARY=es_AR.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=es_AR.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

```bash
$ date '+%A %d %B, %H:%M'
miércoles 01 mayo, 19:28
```

Yabar date config
```css
ya_date:{
        exec: "YABAR_DATE";
        align: "center";
        fixed-size: 250;
        interval: 2;
        internal-prefix: "🕒 ";
        internal-option1: "%A %d %B, %H:%M";
    }
```
